//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 02:14:34 ¿ÀÈÄ KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://codingsam.com")
package jaxb.foodList;
